// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckrnouipaadujzimfdrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrcm5vdWlwYWFkdWp6aW1mZHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDUzMDAsImV4cCI6MjA2ODMyMTMwMH0.aWVw_P1nWi5UbYDH1XmAChoRvSxd2Ahy-1HOf0_MQqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});